[platformio]
default_envs = esp32-s3-devkitc-1

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
monitor_filters = esp32_exception_decoder

; 현재 보드의 CH9102 USB-UART 포트
upload_port = COM10
monitor_port = COM10

; Serial.printf()를 Native USB CDC가 아닌 UART0(CH9102)로 출력한다.
build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=0
